# Simple makefile for simple example
PROGRAM=sleep_test
PROGRAM_SRC_DIR=. 
# The -D directives #define constants to enable things in httpd.h
EXTRA_CFLAGS=


# Add any modules from the 'extras' folder in esp-open-rtos here.
EXTRA_COMPONENTS=

# spiffs configuration
FLASH_SIZE = 32
SPIFFS_BASE_ADDR = 0x200000
SPIFFS_SIZE = 0x010000

# SPIFFS_SINGLETON = 0  # for run-time configuration


include /usr/local/esp8266/esp-open-rtos/common.mk

